language: node_js

node_js:
    - '4.1'

before_install:
    - npm install -g npm@latest

deploy:
    provider: npm
    email: peterc@aetheric.co.nz
    api_key:
        secure: AFmkTXJDP+xkxdx8uh6ssls6LxYlwPNp9xoiaILkM4ewQ+8ho+pmg7/0x13+aXDEK7Io6vkUp+qyHo0jKHkJkC2lyC5sXmxWEaugTc2723leZEYyg+6k650bS+baAGfWtyyjf7rXoZfWDCPmebFySK7drwozC/JdSqvZbuUV+Mz9e2J7qDBlC0NNLXc6DTHdeQ0FMQufMq2G8rX3Mqa8CeRvpzBchraRv9q4iMdPHo/xp2aoBkm7kg+3Y/vR17hmG3ZuHb8UCRkEPeLwjpgb1jAtx/170zj3ONtUoXAcD61y2emKOSW7FALWAqAhojNJeMGpwCZpFmwf7gboMSQaa1D8PmIVp2KuCfAPEauGnHht2Gntf5hRUg3KHBmbO4EcNPTztFYkyAOERFp4rZrLPcfk0PSYJUBHZrhmeWs+nQF96dudTBx1l3r+v7g57PBRGbinOKz6BZH7LDP+u2Y3WFtwowz1uVvRpQ9cL1Ku3jMbt9Vv+ik53AyeqHhrNEBXz1V4mqWu8i6nL4m/l0NgnOt7tzWki8oybAME1wiGWPCYRgtWDkIamTYbYpZaRNNsPG9BL+aqT4JOo5pqwCs1RKDI/DYqMeGuvjKAbN/aM2Qyn65BCC2KHFhBYmxumX3DhdzW97lnw/6It4xd7pWLtzKQBySqmbpFZUIYov+JzkE=
    on:
        repo: aetheric/gulp-recipe-browserify
        tags: true

